### PR TITLE
implemented  the PA=LDU algorithm

### PR DESCRIPTION
**Pull request by yijunyu**
Implemented the PA=LDU algorithm with pivoting using the Yacas language. 
It works for constant valued matrices, but may have trouble when the matrix A contains symbols. 
Is there a way to include a symbolic expression in the If statement? 

For example,

In> If(a^2-b^2,1,-1)
net.sf.yacas.YacasException: In function "If" : 
bad argument number 1(counting from 1) : 

The offending argument a^2-b^2 evaluated to a^2-b^2

### CODE REVIEW

**Comment by grzegorzmazur** [comment]
Hi,

Thanks a lot for the patch!

Regarding your question with symbolic expressions - there's no ultimate solution to that. After all, when we have an arbitrary expression, there's no way to decide if it's zero or not. It can be mitigated in two ways I know of. The first approach is used by maxima, and it boils down to asking the user, in the runtime, if given expression, encountered during calculations, is zero or not. While being possibly the best one, I don't really like it - I happen to run quite long calculations in batch mode, and this means that no user interaction is possible. The other way depends on ability to make assumptions on certain symbols. If you could state that a < b, the program would be able to conclude that a^2-b^2 < 0 => a^2-b^2 != 0. AFAIR mathematica allows for that. Something along this ways is implemented in sage (http://doc.sagemath.org/html/en/reference/calculus/sage/symbolic/assumptions.html). While this approach has some weaknesses, I'd be happy to have it implemented in yacas. Unfortunately, it's quite a challenge, and I haven't even started working on it. 

So for now there's no good way to decide in general if a certain expression is 0 or not. And, even with assumptions implemented, such situations may happen, so working around it seems to be the only option.

BTW - your patch contains both the previous work and the new one. Could you please try rebasing your repo to the current develop state? This way you may avoid conflicts.

Thanks,
Grzesiek

**Comment by yijunyu** [comment]
Hi Grzesiek,

Thanks a lot for explaining not only one, but two, possible ways to deal with the problem.

I checked the documentation of Yacas for a while and found some workaround by
doing something differently. This time, I am making a “bold” assumption
that as long as the expression is not constant (Type(expo)!=“”) and is not 0, it is possible
it is not zero. In that case, I can safely use the variable as a non-zero element to carry on with
the elimination. Plus, the original algorithm of pivoting in the book needs to compute the “max”
of the column just for obtaining numerically more stable results. If we aim for symbolic computation,
this won’t be an issue. Taking this into account, I decided to pick any non-zero row to swap with
the pivot one.

When it was applied to a few examples, including those with 0 pivots, I managed to achieve the
desired results.

After handling another urgent task, I will rebase the patches and push again to resolve the conflicts
so you can have a look.

Cheers — Yijun

On 9 Jun 2016, at 18:03, Grzegorz Mazur <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Thanks a lot for the patch!

Regarding your question with symbolic expressions - there's no ultimate solution to that. After all, when we have an arbitrary expression, there's no way to decide if it's zero or not. It can be mitigated in two ways I know of. The first approach is used by maxima, and it boils down to asking the user, in the runtime, if given expression, encountered during calculations, is zero or not. While being possibly the best one, I don't really like it - I happen to run quite long calculations in batch mode, and this means that no user interaction is possible. The other way depends on ability to make assumptions on certain symbols. If you could state that a < b, the program would be able to conclude that a^2-b^2 < 0 => a^2-b^2 != 0. AFAIR mathematica allows for that. Something along this ways is implemented in sage (http://doc.sagemath.org/html/en/reference/calculus/sage/symbolic/as sumption s.html<http://doc.sagemath.org/html/en/reference/calculus/sage/symbolic/assumptions.html>). While this approach has some weaknesses, I'd be happy to have it implemented in yacas. Unfortunately, it's quite a challenge, and I haven't even started working on it.

So for now there's no good way to decide in general if a certain expression is 0 or not. And, even with assumptions implemented, such situations may happen, so working around it seems to be the only option.

BTW - your patch contains both the previous work and the new one. Could you please try rebasing your repo to the current develop state? This way you may avoid conflicts.

Thanks,
Grzesiek

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/grzegorzmazur/yacas/pull/205#issuecomment-224960293>, or mute the thread<https://github.com/notifications/unsubscribe/AA1_GFt5Nlum_0rlGgxQKqwTSPIt-2xnks5qKEdPgaJpZM4IxuPJ>.

-- The Open University is incorporated by Royal Charter (RC 000391), an exempt charity in England & Wales and a charity registered in Scotland (SC 038302). The Open University is authorised and regulated by the Financial Conduct Authority.

**Comment by grzegorzmazur** [comment]
Thanks a lot! BTW, instead of having Inverse(), InverseD(), InverseL() and InverseU() I've overloaded Inverse() to use specific algorithm depending on the type of the matrix passed as argument; would you mind checking if I haven't introduced any bug in your code in the process?

Thanks,
Grzesiek

**Comment by yijunyu** [comment]
Hi Grzesiek,

Have you recently changed the “Inverse” function in the develop branch ?

The computation of InverseD, InverseL and InverseU was not based on the Inverse(), but based on the PLDU routine. But the ones merged in #205 might contain a bug that I just fixed in the new version of “develop” branch
in my local repository. I haven’t created a new pull request yet :-)

I will check out your changes and see if they are consistent, then request to pull.

BTW, I intend to cite YACAS in a paper I am writing. The documentation of the tool has paper1 and paper2, on the DBLP, I could find the shorter one as follows:


  *
Ayal Z. Pinkus<http://dblp.uni-trier.de/pers/hd/p/Pinkus:Ayal_Z=>, Serge Winitzki: "YACAS: A Do-It-Yourself Symbolic Algebra Environment". AISC 2002<http://dblp.uni-trier.de/db/conf/aisc/aisc2002.html#PinkusW02>: 332-336

Do you know if paper2 has been published somewhere so I can cite it instead?

Cheers — Yijun

On 15 Jun 2016, at 16:10, Grzegorz Mazur <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks a lot! BTW, instead of having Inverse(), InverseD(), InverseL() and InverseU() I've overloaded Inverse() to use specific algorithm depending on the type of the matrix passed as argument; would you mind checking if I haven't introduced any bug in your code in the process?

Thanks,
Grzesiek

**Comment by yijunyu** [comment]
Hi Grzesiek,

It’s me again. I have looked at the “develop” branch with the overloaded functions. One thing I am not too sure is about the precedence of these functions.
E.g., both IsDiagonal(), isLowerTriangular(), and IsUpperTriangular() could all be satisfied at the same time. Would the simpler one be invoked first by the
lexical order of their appearance in the library ?

Cheers — Yijun


On 15 Jun 2016, at 16:10, Grzegorz Mazur <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks a lot! BTW, instead of having Inverse(), InverseD(), InverseL() and InverseU() I've overloaded Inverse() to use specific algorithm depending on the type of the matrix passed as argument; would you mind checking if I haven't introduced any bug in your code in the process?

Thanks,
Grzesiek

**Comment by grzegorzmazur** [comment]
Strictly speaking these are rewriting rules, not functions. And in the case of rewriting rules (contrary to functions) it is possible to manually specify the precedence; the numbers in front of the # sign define it. Otherwise the precedence is undefined (rules with no precedence order or at the same precedence order are matched in completely arbitrary sequence). That's why I assigned the lowest order (which is highest precedence) to diagonal matrix, then triangular and then general.

Cheers,
Grzesiek

**Comment by yijunyu** [comment]
Thank you Grzesiek for the explanation, I will go for it. Let me fix the problem in InverseL / InverseU then commit again after changing the computation using the overloaded functions.

Cheers — Yijun

On 15 Jun 2016, at 17:09, Grzegorz Mazur <notifications@github.com<mailto:notifications@github.com>> wrote:


Strictly speaking these are rewriting rules, not functions. And in the case of rewriting rules (contrary to functions) it is possible to manually specify the precedence; the numbers in front of the # sign define it. Otherwise the precedence is undefined (rules with no precedence order or at the same precedence order are matched in completely arbitrary sequence). That's why I assigned the lowest order (which is highest precedence) to diagonal matrix, then triangular and then general.

Cheers,
Grzesiek

**Comment by grzegorzmazur** [comment]
Hi Yijun,

Excellent :) Just if you could please first refresh your local repository copy from my repository (rebase or merge, whichever you prefer). This way only new code will make it to the pull request (otherwise you most likely resubmit all previous changes).

Thanks,
Grzesiek

**Comment by yijunyu** [comment]
Hi Grzesiek,

Yes, I have just merged your changes locally, fixed the bugs I know and removed the redundant functions. Will do pull request now.

Cheers — Yijun

On 15 Jun 2016, at 17:17, Grzegorz Mazur <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Yijun,

Excellent :) Just if you could please first refresh your local repository copy from my repository (rebase or merge, whichever you prefer). This way only new code will make it to the pull request (otherwise you most likely resubmit all previous changes).

Thanks,
Grzesiek

**Comment by grzegorzmazur** [comment]
Great, thanks a lot!

BTW, I've got followup questions. What you think about replacing the original Inverse() function (the general square matrix variant) with your InversePLDU()? Unless I've missed something, it should be always a win, right? The other question is just nitpicking. You can display matrices using PrettyForm(matrix) - would this be enough for you or you insist on keeping the PrintMatrix() function?

Thanks,
Grzesiek

**Comment by yijunyu** [comment]
Yes, InversePLDU can replace Inverse.

I will try PrettyForm (sorry for not knowing it), if it works, I will remove PrintMatrix :-)

Cheers — Yijun

On 16 Jun 2016, at 14:51, Grzegorz Mazur <notifications@github.com<mailto:notifications@github.com>> wrote:


Great, thanks a lot!

BTW, I've got followup questions. What you think about replacing the original Inverse() function (the general square matrix variant) with your InversePLDU()? Unless I've missed something, it should be always a win, right? The other question is just nitpicking. You can display matrices using PrettyForm(matrix) - would this be enough for you or you insist on keeping the PrintMatrix() function?

Thanks,
Grzesiek

**Pull request merged**
